const CRITICAL_PREFIXES=['accounting.immutable_posting','accounting.posting_hash_chain','accounting.period_locks','close.','identity.','security.tenant_rls','security.server_secrets','workflow.signed_','workflow.approval_','audit.human_decision','audit.evidence_isa230','tax.rule_versions','tax.effective_dated_engine','brain.no_fabricated_refs'];
const HIGH_PREFIXES=['accounting.','ar.','ap.','reconciliation.','procurement.','treasury.','assets.','inventory.','budgeting.','intercompany.','revenue.','lease.','import.','audit.','tax.','ai.','brain.','reports.','ops.retention','ops.legal_hold'];
const LOW_PREFIXES=['theme.','ux.','reader.','audio.','media.','dev.','labs.'];
const VERIFIED=new Map([
 ['accounting.money_minor_units','parity_verified'],['accounting.arabic_number_normalization','parity_verified'],['accounting.journal_validation','parity_verified'],
 ['accounting.immutable_posting','in_progress'],['accounting.reversals','in_progress'],['accounting.posting_hash_chain','in_progress'],['accounting.period_locks','in_progress'],['accounting.depreciation','in_progress'],
 ['reconciliation.deterministic_match','in_progress'],['reconciliation.ledger_candidates','in_progress'],
 ['audit.engagement_lifecycle','in_progress'],['audit.materiality','in_progress'],['audit.sampling_systematic','in_progress'],['audit.evidence_isa230_bundle','in_progress'],
 ['ar.receipt_allocation','in_progress'],['ap.payment_allocation','in_progress'],['assets.depreciation_run','in_progress'],
 ['ai.advisory_only','in_progress'],['brain.citations','in_progress'],
 ['identity.rbac','in_progress'],['identity.separation_of_duties','in_progress'],['security.tenant_rls','in_progress'],['security.server_secrets','in_progress'],
 ['requirements.registry','in_progress'],['requirements.parity_gate','in_progress']
]);
const DEPS={
 foundation:[],accounting:['contracts'],ar:['contracts','accounting'],ap:['contracts','accounting'],reconciliation:['contracts','accounting'],procurement:['contracts','ap','inventory','accounting'],treasury:['contracts','accounting','reconciliation'],assets:['contracts','accounting'],inventory:['contracts','accounting'],close:['contracts','accounting','ar','ap','treasury','assets','inventory','tax'],budgeting:['contracts','accounting'],intercompany:['contracts','accounting','reconciliation'],revenue:['contracts','accounting','ar'],lease:['contracts','accounting'],
 audit:['contracts','accounting','evidence'],reporting:['contracts','accounting','audit'],analytics:['contracts','accounting'],tax:['contracts','accounting'],import_export:['contracts','accounting'],knowledge_brain:['contracts'],ai:['contracts','knowledge_brain'],workflow:['contracts'],library_reader:['contracts'],audio_media:['contracts','library_reader'],sales:['contracts','accounting'],security:['contracts'],operations:['contracts'],requirements:['contracts'],developer_quality:['contracts'],design_ux:['contracts'],pwa_offline:['contracts','design_ux'],labs:['contracts']
};
const FINANCIAL_MODULES=new Set(['accounting','ar','ap','reconciliation','procurement','treasury','assets','inventory','close','budgeting','intercompany','revenue','lease','tax']);
export function riskClass(id){if(CRITICAL_PREFIXES.some(x=>id.startsWith(x)))return'critical';if(HIGH_PREFIXES.some(x=>id.startsWith(x)))return'high';if(LOW_PREFIXES.some(x=>id.startsWith(x)))return'low';return'normal'}
export function parityStatus(id){return VERIFIED.get(id)||'not_started'}
export function authorityClass(cap){if(cap.module==='ai')return'advisory_only';if(FINANCIAL_MODULES.has(cap.module))return'deterministic_domain';if(cap.module==='audit')return'deterministic_plus_human_signoff';if(['design_ux','pwa_offline','audio_media','library_reader'].includes(cap.module))return'presentation_or_user_preference';if(cap.module==='labs')return'test_only';return'deterministic_or_human'}
export function dependencies(cap){return{module_dependencies:DEPS[cap.module]||['contracts'],forbidden_dependencies:FINANCIAL_MODULES.has(cap.module)?['ai']:[]}}
function genericId(id,suffix='GATE'){return id.toUpperCase().replace(/[^A-Z0-9]+/g,'-')+'-'+suffix}
export function acceptance(cap){const id=cap.id;const specific={
 'accounting.money_minor_units':[{id:'MONEY-001',given:'Arabic, Persian or Latin digit amount',when:'parseMoney executes',then:['exact bigint minor units','no floating-point equality']},{id:'MONEY-002',given:'invalid input',when:'parseMoney executes',then:['INVALID_MONEY','no zero coercion']}],
 'accounting.journal_validation':[{id:'JRN-001',given:'balanced lines',when:'validateJournal executes',then:['valid=true','debit equals credit']},{id:'JRN-002',given:'unbalanced lines',when:'validateJournal executes',then:['valid=false','JOURNAL_UNBALANCED']}],
 'accounting.immutable_posting':[{id:'POST-001',given:'approved balanced journal in open period',when:'authorized post command executes',then:['one posting event','journal posted','hash and audit event persisted']},{id:'POST-002',given:'posted journal',when:'update or delete is attempted',then:['database rejects mutation','no accounting state changes']},{id:'POST-003',given:'same idempotency key and payload',when:'posting retries',then:['original result','no duplicate financial effect']}],
 'reconciliation.deterministic_match':[{id:'REC-001',given:'bank and ledger lines with same exact amount',when:'candidate generation runs',then:['amount remains bigint minor units','date tolerance is enforced','match score is explainable']},{id:'REC-002',given:'competing candidates',when:'single-use allocation runs',then:['one bank line maps at most once','one ledger line maps at most once']}],
 'audit.engagement_lifecycle':[{id:'AUD-001',given:'engagement',when:'transition requested',then:['only next stage allowed','blockers and required gates enforced']},{id:'AUD-002',given:'successful transition',when:'persisted',then:['actor and human decision reference retained']}],
 'audit.materiality':[{id:'MAT-001',given:'positive benchmark and approved basis-point policy',when:'materiality calculates',then:['exact minor-unit overall materiality','exact performance materiality','exact clearly-trivial threshold']},{id:'MAT-002',given:'invalid benchmark or rate',when:'materiality calculates',then:['stable validation error','no binding result']}],
 'audit.sampling_systematic':[{id:'SMP-001',given:'population, sample size and seed',when:'systematic sampling runs twice',then:['identical selected units','requested sample size']}],
 'audit.evidence_isa230_bundle':[{id:'EVD-001',given:'same ordered evidence bundle',when:'Merkle root is calculated',then:['deterministic root','canonical field ordering']},{id:'EVD-002',given:'same preparer and reviewer',when:'bundle sealing is requested',then:['SEPARATION_OF_DUTIES_VIOLATION','no seal created']}],
 'ar.receipt_allocation':[{id:'AR-ALLOC-001',given:'receipt and customer open items',when:'allocation runs',then:['exact minor-unit allocations','no allocation exceeds open balance','no allocation exceeds receipt']}],
 'ap.payment_allocation':[{id:'AP-ALLOC-001',given:'payment and vendor open items',when:'allocation runs',then:['exact minor-unit allocations','no allocation exceeds open balance','no allocation exceeds payment']}],
 'accounting.depreciation':[{id:'FA-DEP-001',given:'cost residual and useful life',when:'straight-line schedule runs',then:['sum of depreciation equals depreciable amount','ending NBV equals residual exactly']}],
 'ai.advisory_only':[{id:'AI-GOV-001',given:'model output contains authority fields',when:'governance normalization runs',then:['authority fields stripped recursively','advisory content retained']},{id:'AI-GOV-002',given:'AI requests binding financial tool',when:'tool authorization runs',then:['AI_AUTHORITY_FORBIDDEN','no command executes']}],
 'brain.citations':[{id:'CITE-001',given:'professional answer',when:'citation validation runs',then:['source version required','block required','page required','checksum required']},{id:'CITE-002',given:'no citations',when:'professional answer is finalized',then:['CITATION_REQUIRED','answer cannot be represented as sourced']}],
 'security.tenant_rls':[{id:'RLS-001',given:'actor scoped to organization A',when:'organization B is queried',then:['no rows returned','write rejected']},{id:'RLS-002',given:'tenant mutation',when:'organization scope missing',then:['fail closed','no cross-tenant state change']}]
};
let a=specific[id]||[{id:genericId(id),given:'capability proposed for parity_verified',when:'contract gate runs',then:['implementation evidence linked','automated tests linked','risk and authority policy pass','placeholder evidence rejected']}];
if(riskClass(id)==='critical'&&parityStatus(id)!=='not_started'&&a.length<2)a=[...a,{id:genericId(id,'SAFETY'),given:'critical capability guard fails',when:'operation executes',then:['fail closed','no partial binding mutation','stable error code']}];return a}
export function evidence(id){const map={
 'accounting.money_minor_units':['packages/accounting/test/money.test.mjs'],'accounting.arabic_number_normalization':['packages/accounting/test/money.test.mjs'],'accounting.journal_validation':['packages/accounting/test/journal.test.mjs'],
 'accounting.immutable_posting':['packages/data/migrations/0002_accounting.sql','packages/accounting/test/posting.test.mjs'],'accounting.reversals':['packages/accounting/test/posting.test.mjs'],'accounting.posting_hash_chain':['packages/accounting/test/posting.test.mjs'],'accounting.depreciation':['packages/assets/test/depreciation.test.mjs'],
 'reconciliation.deterministic_match':['packages/reconciliation/test/matcher.test.mjs'],'reconciliation.ledger_candidates':['packages/reconciliation/test/matcher.test.mjs'],
 'audit.engagement_lifecycle':['packages/audit/test/lifecycle.test.mjs','packages/data/migrations/0003_audit.sql'],'audit.materiality':['packages/audit/test/materiality.test.mjs'],'audit.sampling_systematic':['packages/audit/test/sampling.test.mjs'],'audit.evidence_isa230_bundle':['packages/evidence/test/bundle.test.mjs'],
 'ar.receipt_allocation':['packages/subledgers/test/open-items.test.mjs'],'ap.payment_allocation':['packages/subledgers/test/open-items.test.mjs'],'assets.depreciation_run':['packages/assets/test/depreciation.test.mjs'],
 'ai.advisory_only':['packages/ai/test/governance.test.mjs'],'brain.citations':['packages/knowledge/test/citation.test.mjs'],
 'security.tenant_rls':['packages/data/migrations/0001_foundation.sql','packages/security/test/policy.test.mjs']};return map[id]||[]}
export function enrich(cap){const risk=riskClass(cap.id);const status=parityStatus(cap.id);return{...cap,risk_class:risk,parity_status:status,authority_class:authorityClass(cap),signing_policy:risk==='critical'?{policy:'four_eyes_when_binding',preparer_may_approve:false}:{policy:risk==='high'?'authorized_domain_policy':'standard'},dependency_policy:dependencies(cap),acceptance_criteria:acceptance(cap),evidence:evidence(cap.id),test_policy:risk==='critical'?{invariants:'100%',integration:'required',security:'required',e2e:'required'}:risk==='high'?{integration:'required',security:'required'}:{interaction_or_unit:'required'},performance_envelope:{status:'benchmark_required_before_production'}}}
